using Accounts.API.Abstractions;
using System.Security.Cryptography;
using System.Text;

namespace Accounts.API.Crypto
{
    public class AesSymmetricEncryptionManager : IAesSymmetricEncryptionManager
    {
        public string EncryptSymmetric(string data, string key, string initializationVectorString)		    // used by private internal api to encrypt rsa key before sending to public api
        {
            byte[] initializationVector = Encoding.ASCII.GetBytes(initializationVectorString);              // must be 16 bytes for block size

            using (Aes aes = Aes.Create())
            {
                aes.Key = Encoding.UTF8.GetBytes(key);
                aes.IV = initializationVector;
                var symmetricEncryptor = aes.CreateEncryptor(aes.Key, aes.IV);

                using (var memoryStream = new MemoryStream())
                {
                    using (var cryptoStream = new CryptoStream(memoryStream as Stream, symmetricEncryptor, CryptoStreamMode.Write))
                    {
                        using (var streamWriter = new StreamWriter(cryptoStream as Stream))
                        {
                            streamWriter.Write(data);
                        }
                        return Convert.ToBase64String(memoryStream.ToArray());
                    }
                }
            }
        }

        public string DecryptSymmetric(string encryptedText, string key, string initializationVectorString)         // used by public api to decrypt rsa key received from private internal api 
        {
            byte[] initializationVector = Encoding.ASCII.GetBytes(initializationVectorString);                      // must be 16 bytes for block size

            byte[] buffer = Convert.FromBase64String(encryptedText);
            using (Aes aes = Aes.Create())
            {
                aes.Key = Encoding.UTF8.GetBytes(key);
                aes.IV = initializationVector;
                var symmetricDecryptor = aes.CreateDecryptor(aes.Key, aes.IV);

                using (var memoryStream = new MemoryStream(buffer))
                {
                    using (var cryptoStream = new CryptoStream(memoryStream as Stream, symmetricDecryptor, CryptoStreamMode.Read))
                    {
                        using (var streamReader = new StreamReader(cryptoStream as Stream))
                        {
                            return streamReader.ReadToEnd();
                        }
                    }
                }
            }
        }

    }
}

// AES Keys are generated by populating byte[32] with random bytes and converting to base 64 string - should be rotated
// SET USER SECRETS FOR AES SYMMETRIC ENCRYPTION (USED TO ENCRYPT AND DECRYPT RSA ASYMMETRIC PUBLIC KEY)
// dotnet user-secrets set "IntAcctsAesSymEncryption:Key" "---"		// dotnet user-secrets set "IntAcctsAesSymEncryption:IV" "---"
// RETRIEVE USER SECRETS FOR AES SYMMETRIC ENCRYPTION (USED TO ENCRYPT AND DECRYPT RSA ASYMMETRIC PUBLIC KEY)
// string accountAesKey = _configuration["IntAcctsAesSymEncryption:Key"];	// string? accountIV = _configuration["IntAcctsAesSymEncryption:IV"];
